"""first commit

Revision ID: d9f1705155c2
Revises: 
Create Date: 2021-12-12 22:49:06.870225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f1705155c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('average_times',
    sa.Column('avg_id', sa.Integer(), nullable=False),
    sa.Column('avg_time', sa.Float(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('record_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['users.name'], ),
    sa.PrimaryKeyConstraint('avg_id')
    )
    op.create_table('times',
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('sc_code', sa.Text(), nullable=False),
    sa.Column('avg_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['avg_id'], ['average_times.avg_id'], ),
    sa.PrimaryKeyConstraint('time_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('times')
    op.drop_table('average_times')
    op.drop_table('users')
    # ### end Alembic commands ###
